baseURL = "https://blog.e0ne.info/"
languageCode = "en-us"
title = "e0ne's comments"
theme = "e0ne-hugo"

[author]
  name = "Ivan Kolodyazhny"
  email = "e0ne@e0ne.info"

  github = "e0ne"
  twitter = "e0ne"
  facebook = "ivan.kolodyazhny"
  linkedin = "ivankolodyazhny"
  youtube = "UCbLJnzbTU83-htkXQykqgAg"

#[permalinks]
#   post = "/:year/:filename"

[taxonomies]
   tag = "tags"
   category = "category"
   archive = "archives"
